language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gfortran python python-dev subversion git swig python-scipy python-numpy python-matplotlib
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - "./build.sh"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib nose
# command to run tests
script:
  - cd hklgen
  - PYTHONPATH=$PYTHONPATH:. nosetests -vv
