# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160609_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atom',
            name='isotope',
            field=models.CharField(max_length=3),
        ),
    ]
