# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160609_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atom',
            old_name='thermal',
            new_name='space',
        ),
    ]
