# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160609_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atom',
            old_name='space',
            new_name='thermal',
        ),
    ]
