# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160610_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='wyckoff',
        ),
    ]
